- src/api/models.py
> [models]: Add relationships for new Exercise model

- src/api/routes.py
```
`"""
This module takes care of starting the API Server, Loading the DB and Adding the endpoints
"""
from flask import Flask, request, jsonify, url_for, Blueprint
from api.utils import generate_sitemap, APIException
from flask_cors import CORS
from api.models import db, Users, Ingredients
from flask_jwt_extended import create_access_token
from flask_jwt_extended import jwt_required
from flask_jwt_extended import get_jwt_identity
api = Blueprint('api', __name__)
CORS(api)
@api.route('/hello', methods=['GET'])
def handle_hello():
response_body = {}
response_body['message'] = "Hello! I'm a message that came from the backend, check the network tab on the google inspector and you will see the GET request"
return response_body, 200
@api.route("/login", methods=["POST"])
def login(): …
```
> [endpoint] feat: post, delete, put with jwt_required

- migrations/versions/7141e64f72f6_.py
- src/api/Ingredients.json
- src/api/models.py
- src/api/routes.py
- Se creó la lista de alimentos en json
- Se hicieron endpoints GETP, PUT, DELETE
- Se modificaron los models
> [endpoint] feat: ingredients, json list ingredients in json file, get/put/delete

- src/api/models.py
- src/api/routes.py
Se han agragado los endpoints de  la IA falta terminar el endpoint de rutinas
> Ai endpoints

- src/front/js/Layout.jsx
- src/front/js/component/MainNavbar.jsx
- src/front/styles/home.css
Pequeña modificación en navbar que faltaba en el merge del jueves; ajuste del total del ancho y la distribución en su caja.
> [home] feat: some settings on navbar and header

- src/api/models.py
- src/api/routes.py
Resuelto el generador de rutinas FIX #12
> Ai endpoint

- src/front/js/component/MainNavbar.jsx
- src/front/js/pages/Home.jsx
- src/front/styles/home.css
- src/front/styles/index.css
- Se realizan cambios en el navbar para ser responsive.
- Se crea un estilo en index.css y se quita de home.css para que el navbar se vea como queremos siendo un componente global sin incorporarlo en cada vista.
- A PARTIR DE ESTE MOMENTO CADA ESTILO PERSONALIZADO EN CSS QUE SE REALIZE DEBE TENER LA PALABA **ESTILO** DELANTE DE SU NOMBRE EN **KEBAB-CASE**: estilo-navbar
> [navbar] fix: navbar responsive añadido estilo en css

- package-lock.json
- package.json
- src/api/routes.py
- src/app.py
- src/front/js/Layout.jsx
- src/front/js/component/MainNavbar.jsx
- src/front/js/pages/GenerateRecipes.jsx
- src/front/js/pages/GenerateRoutines.jsx
- src/front/js/store/flux.js
Aplicado vinculado las rutas de la IA, donde se modifico el MainNAvbar, se crearon las paginas GenerateRoutines y GenerateRecipes
> AI Frontend

- package-lock.json
- package.json
- src/api/admin.py
- src/api/models.py
- src/api/routes.py
- src/front/js/Layout.jsx
- src/front/js/pages/GenerateRecipes.jsx
- src/front/js/pages/GenerateRoutines.jsx
- src/front/js/store/flux.js
Resuelto el bug de favoritos de las recetas y rutinas
> Ai generator

- src/front/js/pages/Login.jsx
- src/front/js/pages/SignUp.jsx
Primer login y signup combinados. **NECESITA PROBAR Y FIXEAR SI ES NECESARIO**
> [login_signup] feat: primer login y signup juntos

- src/app.py
- src/front/js/Layout.jsx
- src/front/js/component/MainNavbar.jsx
- src/front/js/pages/GenerateRecipes.jsx
- src/front/js/store/flux.js
resolved conflict in the layout with duplicated pages
> added tokken expiration to 24h in app.py

- src/front/js/component/Footer.jsx
- src/front/styles/Footer.css
> [footer] feat: footer finalizado

- src/front/js/Layout.jsx
- src/front/js/component/Footer.jsx
- src/front/styles/Footer.css
Se fixea el footer para que permanezca abajo de la página
> [fix-footer] fix: footer bottom

- src/front/js/pages/Login.jsx
Se despega el cuadro de login-signup del navbar
> [login-signup] fix: despegado del navbar

- src/front/js/component/MainNavbar.jsx
Se deja solo un botón para ir al login-signup.
> [navbar] fix: boton unico para login-signup

- src/api/Exercises.json
- src/api/models.py
- src/api/routes.py
- src/front/js/Layout.jsx
- src/front/js/component/MainNavbar.jsx
- src/front/js/pages/Exercise.jsx
Creada la lista de ejercicios con sus respectivos endponts y luego implementado en el front. falta alimentar la base de datos con las imagenes descriptivas de cada ejercicio y traducirlo al español
> Exercises list

- src/front/js/pages/Login.jsx
- src/front/styles/index.css
> fix all app

- src/api/routes.py
- src/front/js/component/BmrCalculator.jsx
- src/front/js/pages/Exercise.jsx
- src/front/js/pages/GenerateRecipes.jsx
- src/front/js/pages/GenerateRoutines.jsx
Se corrigio y unifico en cuanto a funcion y diseño como color de fondo, tamaño de texto y espaciados de los componentes BMRcalculator, Trainers, Exercise, GenerateRecipe, GenerateRoutine
> [CORRECTIONS]

- src/front/js/Layout.jsx
- src/front/js/component/FormTrainer.jsx
- src/front/js/pages/Profile.jsx
> Se ha corregido enlaces rotos y algunos estilos

- src/api/routes.py
- src/front/js/pages/GenerateRecipes.jsx
- src/front/js/pages/GenerateRoutines.jsx
- src/front/js/store/flux.js
mejoras en diseño y funcionamiento de la pagina
> [ENANCEMENT]: Fixed
